### ISSUE TITLE
 Error: Cannot read properties of undefined (reading 'secure')

### ISSUE THREAD

**Issue by ricellis** [IBM/cloudant-node-sdk#1332]
**Describe the bug**

In `0.6.0` the extended scope of cookie handling appears to cause a failure under some circumstances.

**To Reproduce**

I was not able to reproduce with this code on my own account, but the error was reported using:

```
const { CloudantV1 } = require('@ibm-cloud/cloudant')

const cloudantInstance = CloudantV1.newInstance({})

cloudantInstance
    .getUpInformation()
    .then((res) => {
      console.log(`Result: ${JSON.stringify(res.result)}`);
    })
```

```
<path-to-file>/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:319
        var error = new Error();
                    ^

Error: Cannot read properties of undefined (reading 'secure')
    at RequestWrapper.formatError (<path-to-file>/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:319:21)
    at <path-to-file>/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:305:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Expected behavior**

Error can be instantiated without causing another error.

**Screenshots**

**Must gather (please complete the following information):**
 - SDK Version [e.g. 1.2.1] `0.6.0`
 - Node.js Version [e.g. Node.js 18]: 18.18.0
 - Name of service that you're trying to use (if applicable): Cloudant
 - Name of operation that you're trying to invoke (if applicable): getUpInformation

**Additional context**

Moving version back to `0.5.5` resolved the problem.

Also the property `secure` is associated with cookies, so in conjunction with the version change it seems likely that this is related to enabling the cookie jar for all auth types. It should be noted that for the report in question IAM auth was being used.

I was not able to see the failing requests in the server side logs, which probably hints that the failure occurs in the _request_ interceptor before ever reaching the server.

**Comment by ricellis** [comment]
I managed to reproduce this issue.
It occurs when there is an outdated `tough-cookie` dependency around.
Specifically I was able to reproduce it with `tough-cookie@2.5.0` which was the version required by the long deprecated `request` library.

Using a version of `tough-cookie` that matches the required dependency range prevents the problem, so I'm going to close this issue.
