### ISSUE TITLE
authenticating with invalid clientId/clientSecret does not fail

### ISSUE THREAD

**Issue by grant-g** [IBM/cloudant-node-sdk#742]
Setting invalid `clientId` and/or `clientSecret` values in the `authenticator` should cause authentication to fail, even when `authenticator.apikey` is valid.  This was the behaviour in the deprecated Cloudant library, and is also the behaviour with IBM/cloudant/python-sdk (401 error).  However in the node implementation it seems like the authenticator's `clientId` and `clientSecret` are ignored either completely or at least enough to not cause the authentication to fail.

Example snippet:
```
let authenticator = new IamAuthenticator({
    apikey: <aValidIamApiKey>,
    clientId: <aBogusIamClientId>,
    clientSecret: <aBogusIamClientSecret>
});
let asdf = CloudantV1.newInstance({
    authenticator: authenticator,
    serviceUrl: <theCloudantUrl>
});
asdf.getServerInformation().then(
    (response) => {
        // should NOT get here since the clientId and clientSecret are intentionally bogus, but this is where it goes
    },
    (error) => {
        // SHOULD get here since the clientId and clientSecret are intentionally bogus, but alas no failure
    }
);
```

Note that use of all Cloudant APIs continue to work with the bogus client id and secret values, not just `getServerInformation()`.

**Must gather (please complete the following information):**
 - SDK Version:  0.0.25
 - Node.js Version: 14.16.0

**Comment by ricellis** [comment]
I'm not able to reproduce this problem, it works as expected for me:
```js
const authenticator = new IamAuthenticator({
  apikey: '****',
  clientId: 'foo',
  clientSecret: 'bar',
});
```
->
```
Unauthorized: Access is denied due to invalid credentials.
    at RequestWrapper.formatError (/Users/ricellis/Cloudant/repos/sdks/cloudant-node-sdk/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:297:21)
    at /Users/ricellis/Cloudant/repos/sdks/cloudant-node-sdk/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:282:45
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  statusText: 'Unauthorized',
  status: 401,
  code: 401,
  body: '{"errorCode":"BXNIM0309E","errorMessage":"The provided client credentials are incorrect",
  ```

```js
const authenticator = new IamAuthenticator({
  apikey: '****',
  // clientId: 'foo',
  // clientSecret: 'bar',
});
```
->
```
  status: 200,
  statusText: 'OK',
```
